camunda-community-hub/zeebe-cluster-helm

zeebe-cluster/templates/statefulset.yaml
zeebe-cluster/values.yaml

My environment has enabled [Pod Security Policies](https://kubernetes.io/docs/concepts/policy/pod-security-policy/) and it's not recommended to run container as `root`.

Add security context configuration to chart.

---

zeebe-cluster/values.yaml

We need to set proper default values for nodeSelector, tolerations and affinity. If we don't set proper default values({} or []) and you override e.g. nodeSelector you will get warnings from Helm.
e.g.
```
coalesce.go:165: warning: skipped value for nodeSelector: Not a table.
```
The end result is still correct, but it is very annoying to get warnings in the build when we create our Helm chart with overrides for these values

Set proper default values to avoid warnings when overriding

---

zeebe-cluster/templates/statefulset.yaml

Fixes an issue when indenting template for `extraInitContainers`.
**Related issues**
Closes #30

fix: fixes indentation of extraInitContainers

---

zeebe-cluster/templates/statefulset.yaml

Sets `securityContext` under the containers spec.
Closes #17

fix: set securityContext under spec.containers

---

zeebe-cluster/templates/service.yaml
zeebe-cluster/templates/statefulset.yaml

This changes is to aid Istio Service Mesh port selection.
If the port names are not provided e.g.
`helm install zeebe . --debug --dry-run --set=service.http.name=http-web --set=service.gateway.name=grpc-gateway --set=service.internal.name=tcp-internal --set=service.command.name=tcp-command`
then the chart will default to the existing port names.

Make Service and Zeebe Container port names configurable via values.yaml

---

README.md
zeebe-cluster/templates/statefulset.yaml
zeebe-cluster/values.yaml

Adds value `env` which allows users to set custom environment variables on the Zeebe broker pods. The variables should be specified in the raw, standard YAML as expected by Kubernetes.
Closes #44

feat: allow setting custom environment to brokers

---

zeebe-cluster/templates/configmap.yaml
zeebe-cluster/templates/statefulset.yaml

Improves start up shell script to ensure we don't overwrite environment variables that were already set. Also exports a new environment var `K8S_POD_NAME` which passes on the pod's assigned name via the downward API, from which we extract the node ID, contact points, etc. 
Additionally we now only set the advertised host and leave the network host to the default, `0.0.0.0`, as it's not necessary to override, and doing so makes the distribution compatible with most service meshes.
Closes #42

feat: improves startup.sh script

---

README.md
zeebe-cluster/templates/configmap.yaml
zeebe-cluster/templates/gateway-deployment.yaml
zeebe-cluster/templates/gateway-service.yaml
zeebe-cluster/templates/service.yaml
zeebe-cluster/templates/statefulset.yaml
zeebe-cluster/templates/tests/test-connection.yaml
zeebe-cluster/values.yaml

This PR introduces a Service and a Deployment for a Standalone gateway. 
It also flattens the `service.` ports and names to simplify the charts parameters as recommended in the official Helm documentation.

Standalone Gateway by default

---

zeebe-cluster/templates/configmap.yaml

It creates the local (/usr/local/zeebe/exporters) dir before copying present (if any) exporters.

creates local exporters dir

---

zeebe-cluster/templates/gateway-deployment.yaml

Change gateway-deployment readiness port to use .Values.serviceGatewayName if specified in the values.yaml, otherwise default to "gateway".

Change gateway-deployment readiness port to use .Values.serviceGatewayName

---

Makefile
README.md
zeebe-cluster/templates/configmap.yaml
zeebe-cluster/templates/gateway-deployment.yaml
zeebe-cluster/templates/statefulset.yaml
zeebe-cluster/values.yaml

This PR updates the chart to use Zeebe 0.23.0 by default, and updates how we configure Zeebe. This means:
- Default image tag is updated to 0.23.0
- Environment variables in both the broker StatefulSet and the gateway Deployment were updated to the new Spring Boot convention
- `zeebeCfg` value was kept, and is now meant to be arbitrary YAML that can be added as a configuration file. The rest of the configuration file was dropped in favour of environment variables
- Port overrides were corrected for both broker and gateway (previously they were not being set in the config, only on the service)
- `JAVA_TOOL_OPTIONS` was fixed to use folded YAML (see https://helm.sh/docs/chart_template_guide/yaml_techniques/#folded-multi-line-strings)
**TODO**
As this is a draft PR, there's …

feat: upgrade Zeebe to 0.23.0

---

zeebe-cluster/templates/service.yaml

Adds the command API port in the broker service; currently we only expose the monitoring and internal ports.
Closes #57

chore: add command API port in broker service

---

zeebe-cluster/templates/tests/test-connection.yaml

Since we embed templating in values.yaml in `global.zeebe`, we have to tell Helm to explicitly re-template any file we reference it in. This is already done in all other files in this chart, this one file is the only exception.
Fixes https://github.com/zeebe-io/zeebe-cluster-helm/issues/59.

Fix Test Connection pod template

---

README.md
zeebe-cluster/templates/gateway-deployment.yaml
zeebe-cluster/values.yaml

Adds support for env variables on the gateway.
Configuration looks like this:
```yaml
gateway:
replicas: 1
logLevel: warn
env: 
- name: ZEEBE_LOG_APPENDER
value: Stackdriver
```
Tested via `helm template zeebe-cluster`, result for the gateway:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
name: "RELEASE-NAME-zeebe-gateway"
labels:
app.kubernetes.io/name: zeebe-cluster
app.kubernetes.io/instance: RELEASE-NAME
app: "RELEASE-NAME-zeebe-gateway"
annotations:   
spec:
replicas: 1
selector:
matchLabels:
app: "RELEASE-NAME-zeebe-gateway"
template:
metadata:  
labels:
app.kubernetes.io/name: zeebe-cluster
app.kubernetes.io/instance: RELEASE-NAME
app: "RELEASE-NAME-zeebe-gateway"
spec:
containers:
- name: zeebe-cluster-gateway
image: "camunda/zeebe:0.23.1"
imagePullPolicy: …
```

feat(gateway): support arbitary env variables

---

README.md
zeebe-cluster/templates/gateway-deployment.yaml

Adds support for custom annotations on the pods of the gateway's Deployment via a new value `gateway.podAnnotations`. This follows the existing pattern of the other custom annotation blocks.
Closes #65

Allow custom annotations on the gateway Deployment pods

---

README.md
zeebe-cluster/templates/gateway-poddisruptionbudget.yaml
zeebe-cluster/templates/poddisruptionbudget.yaml
zeebe-cluster/values.yaml

Create PodDisruptionBudgets for the gateway deployment and broker statefulset.
By default, PDBs are not created.
https://kubernetes.io/docs/tasks/run-application/configure-pdb/
https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
Fixes #60

Add PodDisruptionBudgets

---

zeebe-cluster/templates/gateway-deployment.yaml

Use pod ip for ZEEBE_GATEWAY_CLUSTER_HOST. This way broker can send messages to this ip to communicate to this gateway.

gateway: use pod ip as cluster host

---

zeebe-cluster/values.yaml

This PR simply bumps the release version to the latest Zeebe version :slightly_smiling_face:

chore: bump default zeebe version

---

zeebe-cluster/values.yaml

Removes the current GC settings as described here https://github.com/zeebe-io/zeebe/issues/4664#issuecomment-646529238
It also removes the PrintFinalFlags, since I see no value in them. It just more annoying then useful, especially if you use jps, jcmd or any other java tool. If you want to see the flag you can run on the pod jcmd <pid> VM.flags -all
Adds `ExitOnOutOfMemoryError` as described here https://github.com/zeebe-io/zeebe-cluster-helm/issues/80#issuecomment-646008695
closes https://github.com/zeebe-io/zeebe-cluster-helm/issues/80

chore(values): remove gc settings

---

zeebe-cluster/Chart.yaml
zeebe-cluster/templates/_helpers.tpl
zeebe-cluster/templates/configmap.yaml
zeebe-cluster/templates/gateway-deployment.yaml
zeebe-cluster/templates/gateway-poddisruptionbudget.yaml
zeebe-cluster/templates/gateway-service.yaml
zeebe-cluster/templates/poddisruptionbudget.yaml
zeebe-cluster/templates/service-monitor.yaml
zeebe-cluster/templates/service.yaml
zeebe-cluster/templates/statefulset.yaml

This PR attempts to standardize our use of labels to a set of well known labels taken from Kubernetes and Helm. All components will have the following common labels:
```yaml
app.kubernetes.io/instance=<RELEASE NAME>
app.kubernetes.io/managed-by=Helm
app.kubernetes.io/name=<CHART NAME>
app.kubernetes.io/version=<APP VERSION>
helm.sh/chart=zeebe-cluster-<CHART VERSION>
```
Additionally, the gateway and the broker will have an `app.kubernetes.io/component=<broker|gateway>` labels, which is applied to all resources pertaining to either.
The PR also standardizes the names of the `ConfigMap` and the `ServiceMonitor` by using the pre-generated `zeebe-cluster.fullname` template which ensures that the given name is compliant with Kubernetes rules about names, and uses a combination of the chart …

chore: standardizes labels

---

zeebe-cluster/values.yaml

The JVM memory limit set by #80/#81 seems a little too stiff to me as people might assign more or less memory to their pods:
>  -Xmx4g
>   -Xms4g
I suggest working with `-XX:MaxRAMPercentage` which has been introduced by Java 10 specifically for container support. 25 or 50 percent for the JVM heap should leave enough memory available for Rocks DB.
Multiple recent sources seem to confirm this direction:
- [Java in a Container: Resource Allocation Guidelines (October 31, 2019)](https://www.ccampo.me/java/docker/containers/kubernetes/2019/10/31/java-in-a-container.html)
- [Playing with the JVM inside Docker Containers (December 3, 2019)](https://blog.nebrass.fr/playing-with-the-jvm-inside-docker-containers/)
- [JVM Memory Settings in a Container Environment (Nov 10, 2018; **partly …

Make JVM memory limit dynamic by setting -XX:MaxRAMPercentage

---

zeebe-cluster/templates/gateway-deployment.yaml

I introduced a bug changing the config map name where the gateway doesn't come up because it had the wrong volume name.
This fixes it - I tested it now deploying a new snapshot benchmark :slightly_smiling_face:

chore: fix gateway config volume name

---

zeebe-cluster/templates/_helpers.tpl

This PR removes mutable information from labels to allow users to upgrade chart/Zeebe versions without having to tear down their previous installations.
Note that this was minimally tested via a single upgrade - happy to hear any other advice there.
EDIT: see https://github.com/zeebe-io/zeebe-cluster-helm/pull/79#issuecomment-662499495 for more

fix: remove transient labels

---

zeebe-cluster/templates/gateway-deployment.yaml
zeebe-cluster/values.yaml

Allow optional configuration for the gateway pod resource limits. Follows the same pattern as the broker statefulset.
Example configuration:
```
gateway:
resources:
requests:
cpu: 200m
memory: 1Gi
```
Fixes #74.

feat(gateway): Add ability to set gateway resource limits

---

zeebe-cluster/templates/gateway-deployment.yaml

Allows users to customize nodeSelector / affinity / toleration settings on the gateway pods. Copied from the statefulset template.

feat(gateway): Enable setting nodeSelector / affinity / tolerations on gateway deployment

---

zeebe-cluster/templates/gateway-deployment.yaml
zeebe-cluster/templates/statefulset.yaml
zeebe-cluster/values.yaml

Add ability to set pod-level labels on both gateway and broker deployments. These labels are not used in the matchSelector.
My specific use case is for Datadog metrics: it uses labels on the pods to attach metadata on the metrics it's gathering from these pods, and we have a set of standard labels on all our applications.
Example configuration on broker pods:
```
podLabels:
labelone: valueone
labeltwo: valuetwo
```
Statefulset excerpt:
```
spec:
replicas: 3
selector:
matchLabels:
app.kubernetes.io/name: zeebe-cluster
app.kubernetes.io/instance: test
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/component: broker
template:
metadata:
labels:
app.kubernetes.io/name: zeebe-cluster
app.kubernetes.io/instance: test
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/component: broker …
```

feat: Add ability to set pod-level labels

---

zeebe-cluster/templates/statefulset.yaml
zeebe-cluster/values.yaml

Adds a toggle that can be used to disable the Elasticsearch exporter. Defaults to enabled for backwards compatibility.

feat(broker): Add ability to disable elasticsearch exporter

---

charts/zeebe-cluster-helm/Chart.yaml

Fixes #104 by updating the chart dependency from prometheus to kube-prometheus-stack which is the new name for the old prometheus-operator chart. Also updated the version to use the latest 12.0.X version

Fixes #104 by updating the chart dependency from prometheus to kube-prometheus-stack

---

charts/zeebe-cluster-helm/values.yaml

This PR updates the elasticsearch and kibana image tags from 6.8.5 to 7.10.1. 
Ref: #114 #115

Update elasticsearch/kibana image tags

---

README.md
charts/zeebe-cluster-helm/templates/gateway-service.yaml
charts/zeebe-cluster-helm/values.yaml

Adding value to parameterize the type of service to be created for the Cluster Gateway.
This will allow us to use the `LoadBalancer` type in the Gateway service to execute `zbctl` commands from outside the kubernetes cluster running on some cloud provider.

Adding value to parameterize the type of service to be created for the Cluster Gateway
